import { Plus_Jakarta_Sans } from "next/font/google";
import "@/styles/styles.scss";

const plusJakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Biovac",
  description: "Generated by Avitex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        {children}
        <div id="nav-full" />
        <div id="nav-sidebar" />
        <div id="overlay" />
        <div id="modal" />
      </body>
    </html>
  );
}
